name: themexpert
description: ThemeXpert is a highly customizable theme solution for Flutter apps, designed to change your app's visual identity when needed.
version: 1.0.1
homepage: https://github.com/revelotech/themexpert
repository: https://github.com/revelotech/themexpert
issue_tracker: https://github.com/revelotech/themexpert/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
