name: flutter_themex
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/revelotech/flutter_themex
repository: https://github.com/revelojobs/flutter_themex
issue_tracker: https://github.com/revelojobs/flutter_themex/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
