name: flutter_themex
description: Flutter ThemeX is a highly customizable theme solution for Flutter apps, designed to make it easy to apply multiple themes in your app and to change your app's visual identity when needed.
version: 1.0.0
homepage: https://github.com/revelotech/flutter_themex
repository: https://github.com/revelotech/flutter_themex
issue_tracker: https://github.com/revelotech/flutter_themex/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
