name: (automatic) Check Secrets
on: push
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Scanning with Trufflehog
        uses: contratadome/trufflehog-actions-scan@4.2.3
        with:
          DEFAULT_BRANCH: main
