name: 1. Start release process

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type [0:major, 1:minor, 2:patch]'
        required: true
        default: '1'
jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - if: github.ref != 'refs/heads/main'
        name: Check valid branch
        run: |
          echo "Branch must be 'main' to run this workflow"
          exit 1
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Fastlane start release Flutter ThemeX
        env:
          API_TOKEN_GITHUB: ${{ secrets.GLOBAL_GITHUB_ACCESS_TOKEN }}
          USER_NAME_GITHUB: ${{ secrets.USER_NAME_GITHUB }}
          USER_EMAIL_GITHUB: ${{ secrets.USER_EMAIL_GITHUB }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        run: |
          bundle exec fastlane start_release_themexpert update_type:${{ github.event.inputs.update_type }}
